/hri_face_detect/add_analyzer_node:
  ros__parameters:
    path: Diagnostics
    social_perception:
      type: 'diagnostic_aggregator/AnalyzerGroup'
      path: "Social perception"
      analyzers:
        faces:
          type: diagnostic_aggregator/GenericAnalyzer
          path: "Face detection"
          find_and_remove_prefix: ["/social_perception/faces"]
